version: '3.7'

services:
  book-api:
    image: apiimage  # Replace with the actual name/tag of your API image
    container_name: book-api
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs  # Expose logs folder

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password