{
 "title": "BookCatalogAPI",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "API Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total API Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_active_seconds_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful API Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_active_seconds_count{outcome=\"SUCCESS\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed API Requests (Errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(outcome) (rate(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg(rate(http_server_requests_active_seconds_sum[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Maximum Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum[1m])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Slow API Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (\n  rate(\n    http_server_requests_seconds_count{method=~\".*GET.*|.*PUT.*|.*DELETE.*\",status=~\".*5.*\",uri=\"/api/books/{id}\"}[1m]\n  )\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (status, uri, method) (\n  rate(\n    http_server_requests_seconds_count{method=~\".*GET.*|.*PUT.*|.*DELETE.*\",status=~\".*4.*\",uri=\"/api/books/{id}\"}[1m]\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Success Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "avg(rate(http_server_requests_active_seconds_sum[1m]) / rate(http_server_requests_active_seconds_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Database Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle Database Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      { "expr": "sum(hikaricp_connections_idle)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Connection Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_timeout_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Connection Usage Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_usage_seconds_sum / hikaricp_connections_usage_seconds_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database Connection Pool Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "sum(hikaricp_connections_max)", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "System Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      { "expr": "process_cpu_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes) / sum(jvm_memory_max_bytes) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "100 - (sum(disk_free_bytes) / sum(disk_total_bytes) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Ready Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "expr": "application_ready_time_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Application Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "application_started_time_seconds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Log Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(logback_events_total{level=\"error\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warning Log Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(logback_events_total{level=\"warn\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Garbage Collection Overhead",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      { "expr": "jvm_gc_overhead", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}